server:
  port: 8081

eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
#        everything should be
management:
  tracing:
    sampling:
      probability: 1.0
