#spring.application.name=configserver

server:
  port: 8088

# Adding configs locally.
spring:
#  application:
#    name: configserver
  cloud:
    config:
      enabled: false

  profiles:
    active: native

